### ISSUE TITLE
Option name list for input parameter

### ISSUE THREAD

**Issue by yunjunz** [bakerunavco/SSARA#6]
It will be more convenient if there is a list for each input parameter, take -p/--platform for example, a complete list of satellite/sensor name, like ALOS, ERS-1, Sentinel-1A, etc. Because sometimes I don't know whether I should use upper case or lower case, with/without "A" for Sentinel-1, Envisat or ENV. 

Same for collectionName also.

If different archives have different keywords for the same platform, SSARA could hardware them and use a unified keyword for users. Or it might be more robust and straight forward if SSARA could recognize any common used name/abbreviation input for platform, like Envisat, ENVISAT, Env, ENV, ASAR all for Envisat.

**Comment by bakerunavco** [comment]
See the wiki page for [Usage Examples](../wiki/Usage-Examples).  The input values are unified for the platform and other keywords, so the [Usage Examples](../wiki/Usage-Examples) will have the correct syntax for those.  Collections, beam mode, swaths are a little more difficult since these number in the 100s of possible values, but you can see the specific values in search results and use those to "filter" or narrow down your queries
